forumsite/forumsite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("posts.urls")),
    path("users/", include("users.urls", namespace="users")),

    path("admin/", admin.site.urls),

]

forumsite/posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostsHome.as_view(), name='home'),
    path('add/', views.AddPost.as_view(), name='add'),
    path('posts/<int:post_id>/<str:status>/', views.react_post, name='react' ),
    path('comments/<int:pk>/<slug:slug>', views.CommentsView.as_view(), name='comments'),
]

forumsite/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/<str:username>/', views.ProfileUser.as_view(), name='profile'),
    path('profile/<str:username>/posts/', views.UsersPosts.as_view(), name='my_posts'),
    path('profile/<str:username>/liked_posts/', views.UsersLikedPosts.as_view(), name='liked_posts'),
    path('profile/<str:username>/disliked_posts/', views.UsersDislikedPosts.as_view(), name='disliked_posts'),

]

forumsite/users/models.py
from django.db import models

# Create your models here.

forumsite/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', max_length=32)
    password = forms.CharField(label='Пароль')

    class Meta:
        model = get_user_model()

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email = email).exists():
            raise forms.ValidationError('Такой email уже существует')
        return email

forumsite/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView

from posts.models import Posts, Like
from users.forms import LoginUserForm, RegisterUserForm
from users.mixins import UsersPostsFilterMixin


# Create your views here.

class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')

class ProfileUser(DetailView):
    model = get_user_model()
    template_name = 'users/profile.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        logged_user = self.request.user #тот кто залогинен
        context["logged_user"] = logged_user.username

        viewed_user = self.kwargs.get('username') #тот кого смотрим
        context['viewed_user'] = get_object_or_404(get_user_model(), username=viewed_user)
        return context


class UsersPosts(UsersPostsFilterMixin):
    empty_list_text = 'У пользователя пока нет постов'
    reaction_type = None


class UsersLikedPosts(UsersPostsFilterMixin):
    empty_list_text = 'У пользователя пока нет лайкнутых постов'
    reaction_type = Like.Status.LIKED


class UsersDislikedPosts(UsersPostsFilterMixin):
    empty_list_text = 'У пользователя пока нет дизлайкнутых постов'
    reaction_type = Like.Status.DISLIKED

forumsite/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Войти</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
     <div class="form-error"> {{ form.non_field_errors }} </div>
    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}"> {{ f.label }} </label> {{ f }} </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="form-btn">Войти</button>

    <p><a href="">Забыли пароль?</a></p>
    <p>В первый раз на нашем сайте? <a href="{% url 'users:register' %}">Зарегистрироваться.</a></p>

</form>

{% endblock %}

forumsite/users/templates/users/my_posts.html
{% extends 'users/profile.html' %}
{% load static %}

{% block posts %}
<div class="blog">
  <hr>
  {% for post in posts %}
  <div class="blog-card">
    <h2> <a href="{% url 'comments' post.id post.slug %}">{{ post.title }}</a> </h2>
    <p>{{ post.content }}</p>
    {% include "posts/partials/blog_card_buttons.html" %}
  </div>
  {% empty %}
  <div class="profile-no-content">
    <img src="{% static 'icons/no_content_guy.png' %}" width="75px">
    <p>{{ empty_list_text }}</p>
  </div>


  {% endfor %}
</div>
{% endblock %}

forumsite/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="profile-wrapper">
    <div class = "profile-main">
        <div class="profile-info">
          <div class = "profile-pic">
            {% if user.photo  %}
              <a href="{% url 'users:profile' user.username %}"><img src="{{ user.photo.url }}" alt="Аватар"></a>
            {% else %}
              <a href="{% url 'users:profile' user.username %}"><img src="{% static 'icons/user.png' %}" alt="Аватар"></a>
            {% endif %}
          </div>
        <h1> {{viewed_user.username}} </h1>
        </div>
        <div class="profile-about-links">
          <a href="{% url 'users:my_posts' viewed_user.username %}">Посты</a>
          <a href="/comments">Комментарии</a>
          <a href="{% url 'users:liked_posts' viewed_user.username %}">"Нравится"</a>
          <a href="{% url 'users:disliked_posts' viewed_user.username %}">"Не нравится"</a>
          <a href="/comments">Скрытые</a>
        </div>
        {% block posts %}

        {% endblock %}
  </div>




</div>



{% endblock %}

forumsite/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<h1>Регистрация</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
     <div class="form-error"> {{ form.non_field_errors }} </div>
        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}"> {{ f.label }} </label> {{ f }} </p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button type="submit" class="form-btn">Войти</button></p>
</form>

{% endblock %}