forumsite/forumsite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("posts.urls")),
    path("users/", include("users.urls", namespace="users")),

    path("admin/", admin.site.urls),

]

forumsite/posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostsHome.as_view(), name='home'),
    path('add/', views.AddPost.as_view(), name='add'),
    path('posts/<int:post_id>/<str:status>/', views.react_post, name='react' ),
    path('comments/<int:pk>/<slug:slug>', views.CommentsView.as_view(), name='comments'),
]

forumsite/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/<str:username>/', views.ProfileUser.as_view(), name='profile'),
    path('profile/<str:username>/posts/', views.UsersPosts.as_view(), name='my_posts'),
    path('profile/<str:username>/liked_posts/', views.UsersLikedPosts.as_view(), name='liked_posts'),
    path('profile/<str:username>/disliked_posts/', views.UsersDislikedPosts.as_view(), name='disliked_posts'),

]

forumsite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
<header>
<script>
    const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    document.cookie = "django_timezone=" + timezone;
</script>

  <div class="container header-container">
      <a href="{% url 'home' %}"><h1 class="logo">Forum</h1></a>
    <div class="header-links">
        {% if user.is_authenticated %}
            <button class="menu-btn"><img class="link" src="{% static 'icons/bubble-chat.png' %}"></button>
            <button onclick="location.href = '{% url 'add' %}'" class="menu-btn"><img class="link" src="{% static 'icons/plus.png' %}">Создать</button>
            <button class="menu-btn"><img class="link" src="{% static 'icons/bell.png' %}"></button>
            <div class="profile-menu-container">
              <button id="profileBtn" class="menu-btn"><img class="link" src="{% static 'icons/user.png' %}"></button>
              <div id="dropdownMenu" class="dropdown hidden">
                <a href="{% url 'users:profile' user.username %}">
                    <img src="{% static 'icons/user.png' %}" class = "dropdownMenu-icon">
                    Просмотр профиля
                </a>
                <a href="/edit-avatar">
                    <img src="{% static 'icons/edit.png' %}" class = "dropdownMenu-icon">
                    Редактировать аватар
                </a>
                <form method="post" action="{% url 'users:logout' %}" style="display: inline; background: none;">
                    {% csrf_token %}
                    <button type="submit" class="dropdownMenu-btn">
                        <img src="{% static 'icons/exit.png' %}" class = "dropdownMenu-icon">
                        <span class="dropdownMenu-text">Выйти</span>
                    </button>
                </form>
              </div>
        </div>
        {% else %}
            <a href="{% url 'users:login' %}" class="login-btn">Войти</a>
        {% endif %}
    </div>
  </div>
</header>


    {% block content %}
    {% endblock %}
     <script src="{% static 'js/main.js' %}" type="module"></script>
</body>
</html>